# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which the frontend will run
EXPOSE 5173

# Build the frontend
RUN npm run build

# Serve the built frontend
CMD ["npm", "run", "start"]
