version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  mongo:
    image: mongo
    volumes:
      - ./data-mongodb:/data/db
    ports:
      - '27017:27017'
